linux-toradex-upstream: backport kbuild switch from lz4c to lz4
Backport mainline kernel patch for switching the kernel image compression
using lz4 insted of lz4c.
This fixes the kernel build issue as seen in the below errors for 32-bit
Toradex modules with the latest OpenEmbedded core master which already
adopted this change in commit fe167e082cbd ("bitbake.conf: require lz4
instead of lz4c").

LZ4     arch/arm/boot/compressed/piggy_data
/bin/sh: 1: lz4c: not found
...
...
ERROR: oe_runmake failed

Related-to: ELB-6050
Signed-off-by: Francesco Dolcini <francesco.dolcini@toradex.com>