layer.conf: drop DANGLINGAPPENDS_WARNONLY
Since bitbake commit fca9c9e3cb6f ("cooker: Drop support for
BB_DANGLINGAPPENDS_WARNONLY"), this variable is not supported and
produces the following error:

ERROR: Variable BB_DANGLINGAPPENDS_WARNONLY support for the variable was
removed as it unconditionally affects all layers (file:
/var/home/frh/bsp-master/build/../layers/meta-toradex-bsp-common/conf/layer.conf
line: 22)

It is safe to remove this variable since there are no append files
(.bbappend) with no corresponding recipe files (.bb).

Signed-off-by: Hiago De Franco <hiago.franco@toradex.com>